// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Company struct {
	ID       int    `json:"Id"`
	Name     string `json:"Name"`
	Location string `json:"Location"`
}

type Job struct {
	JobID       int    `json:"JobId"`
	Title       string `json:"Title"`
	Description string `json:"Description"`
	CompanyID   int    `json:"CompanyId"`
}

type NewCompany struct {
	Name     string `json:"Name"`
	Location string `json:"Location"`
}

type NewJob struct {
	Title       string `json:"Title"`
	Description string `json:"Description"`
	CompanyID   int    `json:"CompanyId"`
}

type NewUser struct {
	Name  string `json:"Name"`
	Email string `json:"Email"`
}

type User struct {
	ID    int    `json:"Id"`
	Name  string `json:"Name"`
	Email string `json:"Email"`
}
